This is the tutorial for the evaluation of CPHF alchemical derivatives using PySCF (version 2.2)  

In [2]:
from pyscf import gto,scf
import numpy as np
import pyscf
pyscf.__version__

'2.2.0'

## Fractional charge molecules

In [3]:
from FcMole import FcM, FcM_like

In [4]:
mol_NN=gto.M(atom= "N 0 0 0; N 0 0 2.1",unit="Bohr", basis="sto-3g") 

The FcM_like function creates a copy of a givem PySCF molecule object with modified nuclear cherges 

In [5]:
fmol=FcM_like(mol_NN,fcs=[.1,-.1])

Only nuclear charges are modified, the number of electrons stays the same

In [6]:
fmol.atom_charges(),fmol.nelec

(array([7.1, 6.9]), (7, 7))

The same result can be achieved using the FcM constructor

In [7]:
fmol1=FcM(fcs=[.2,-.2],atom= "N 0 0 0; N 0 0 2.1",unit="Bohr", basis="sto-3g")

The number of electron matches the atom string

In [8]:
fmol1.atom_charges(),fmol1.nelec

(array([7.2, 6.8]), (7, 7))

If only some atoms have modified nuclear charges is possible to pass as a fcs parameter a double list [[idxs],[fcs]]

In [9]:
fmol2=FcM(fcs=[[0,1],[.3,-.3]],atom= "N 0 0 0; N 0 0 2.1",unit="Bohr", basis="sto-3g")

In [10]:
fmol2.atom_charges(),fmol2.nelec

(array([7.3, 6.7]), (7, 7))

For scf calculations using fractional charges molecules the initial density matrix guess needs to be evaluated from the eigenfunction of the monoelectronic Hamiltonian (there is no single atom density "SAD" matrix guess for atoms with fractional charge)

In [11]:
mf0=scf.RHF(mol_NN)
mf=scf.RHF(fmol)
mf1=scf.RHF(fmol1)
mf2=scf.RHF(fmol2)

In [12]:
mf0.scf()
mf.scf(dm0=mf0.make_rdm1())
mf1.scf(dm0=mf.make_rdm1())
mf2.scf(dm0=mf1.make_rdm1())

converged SCF energy = -107.49885049543
converged SCF energy = -107.513993473609
converged SCF energy = -107.559400858527
converged SCF energy = -107.635008088406


/home/giorgio/anaconda3/lib/python3.8/site-packages/pyscf/gto/mole.py:1209: UserWarning: Function mol.dumps drops attribute with_rinv_at_nucleus because it is not JSON-serializable
  warnings.warn(msg)


-107.63500808840597

For sto basis sets sometimes the scf fails to converge with a H1 initial DM

In [16]:
mf0.scf()
mf.scf(dm0=mf.init_guess_by_1e())
mf1.scf(dm0=mf1.init_guess_by_1e())
mf2.scf(dm0=mf2.init_guess_by_1e())

converged SCF energy = -107.49885049543
converged SCF energy = -106.801217627226
converged SCF energy = -106.846028831322
converged SCF energy = -106.921050773896


-106.92105077389586

But with 6-31g basis sets the scf converges more reliably

In [17]:
mol_NN631=gto.M(atom= "N 0 0 0; N 0 0 2.1",unit="Bohr", basis="6-31g") 
fmol=FcM_like(mol_NN631,fcs=[.1,-.1])
fmol1=FcM_like(mol_NN631,fcs=[.2,-.2])
fmol2=FcM_like(mol_NN631,fcs=[.3,-.3])
mf0=scf.RHF(mol_NN631)
mf=scf.RHF(fmol)
mf1=scf.RHF(fmol1)
mf2=scf.RHF(fmol2)


In [18]:
mf0.scf()
mf.scf(dm0=mf.init_guess_by_1e())
mf1.scf(dm0=mf1.init_guess_by_1e())
mf2.scf(dm0=mf2.init_guess_by_1e())

converged SCF energy = -108.866441669076
converged SCF energy = -108.885543919002
converged SCF energy = -108.942880098699
converged SCF energy = -109.038539520767


-109.03853952076655

In [19]:
mf0.scf()
mf.scf(dm0=mf0.make_rdm1())
mf1.scf(dm0=mf.make_rdm1())
mf2.scf(dm0=mf1.make_rdm1())

converged SCF energy = -108.866441669076
converged SCF energy = -108.885543919001
converged SCF energy = -108.942880098699
converged SCF energy = -109.038539520765


-109.03853952076524